# Computer Programming 0917

In [1]:
# Ignore this; my laptop is so old and Apple is nasty so I need this
sdkroot = !xcrun --show-sdk-path
%env SDKROOT={sdkroot[0]}

env: SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk


## More on terminal commands

- `man pwd`: open the MANual page of the command `pwd`
- `man cd`: open the MANual page of the command `cd`
- `man ls`: open the MANual page of the command `ls`
- `pwd`: Print Working Directory
- `cd 0917`: Change Directory to the folder called `0917`
- `cd ..`: Change Directory to the parent directory
- `cd -`: Change Directory to the previous directory (last page)
- `cd ~`: Change Directory to the home directory
- `mkdir`: Make new Directory (new folder)
- `ls`: LiSt the content of current working directory
- `ls -l`: LiSt with Longer information
- `ls -a`: LiSt All files, including hidden ones
- `ls -la`: equivalent to `ls -l -a`
- `cat`, `hexdump`
- `nano`, `vim`, `code`
- `clear`
- `history`: show the command history
- `touch animal.cpp`: used to create an empty file called `animal.cpp`
- `grep cout animal.cpp`: search for `cout` in the file `animal.cpp`
- `grep "cout <<" animal.cpp`: search for `cout <<` in the file `animal.cpp` (quote the space)
- `head animal.cpp`: shows the first 10 lines of `animal.cpp`
- `head -n 100 animal.cpp`: first 100 lines
- `tail animal.cpp`: shows the last 10 lines of `animal.cpp`
- `tail -n 1000 animal.cpp`: last 1000 lines
- `rm animal.cpp`: ReMoves (deletes) the file `animal.cpp`.  
- `rm -r 0917`: ReMoves Recursively, including folders and sub-folders and files within
- `rm -f 0917/animal.cpp`: ReMoves files with Force (no confirmation)
- `ｒｍ -ｒｆ /`: ReMoves everything, starting from the root.
  DON'T DO THIS.  YOUR COMPUTER WILL BREAK.
- `mv animal.cpp 0917/monster.cpp`: MoVes `animal.cpp` to folder `0917` and rename it `monster.cpp`
- `cp animal.cpp animal-new.txt`: CoPies `animal.cpp` paste it as `animal-new.txt`
- Use `-r` to copy directories recursively: `cp -r 0917 0924`
- `g++-14 -std=c++26 -Wall -Wextra -Wpedantic animal.cpp -o an`:
  compile `animal.cpp` to `an` with all the warning enabled.
- `./an`: execute `an`
- `./an <<< "retire"`: execute `an` with input `retire`.
- `./an < keep.txt`: execute `an` with input coming from a text file `keep.txt`.
- `./an > noise.txt`: execute `an` but all `cout` goes to `noise.txt` (overwrite).
- `./an >> noise.txt`: execute `an` but all `cout` goes to `noise.txt` (append).
- `./an <<< "retire" > noise.txt`: two things at once.
- `./an < keep.txt >> noise.txt`: two things at once.
- `echo retire`: print `retire` to screen
- `echo "retire" | ./an`: execute `an` with input `retire`.
- `./an | grep visitors`: execute `an` but only show lines containing "visitors".
- `./an | grep "is born"`: execute `an` but only show lines containing "is born".
- What does `|` do?
- `Ctrl + C` terminates the program early

## Array

In [2]:
%%writefile array.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100];
    for (int i = 0; i < 10; i++) {
        int k = i*i;
        cout << "Without initialization, the "
        << k << "th element of CocoMelon is "
        << CocoMelon[i] << endl;
    }
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = i;
    }
    for (int i = 0; i < 10; i++) {
        int k = i*i;
        cout << "With initialization, the "
        << k << "th element of CocoMelon is "
        << CocoMelon[i] << endl;
    }
    return 0;
}

Overwriting array.cpp


In [3]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic array.cpp -o array
./array

Without initialization, the 0th element of CocoMelon is -1156002368
Without initialization, the 1th element of CocoMelon is 32759
Without initialization, the 4th element of CocoMelon is 704
Without initialization, the 9th element of CocoMelon is 0
Without initialization, the 16th element of CocoMelon is 0
Without initialization, the 25th element of CocoMelon is 0
Without initialization, the 36th element of CocoMelon is 0
Without initialization, the 49th element of CocoMelon is 0
Without initialization, the 64th element of CocoMelon is -1156001664
Without initialization, the 81th element of CocoMelon is 32759
With initialization, the 0th element of CocoMelon is 0
With initialization, the 1th element of CocoMelon is 1
With initialization, the 4th element of CocoMelon is 2
With initialization, the 9th element of CocoMelon is 3
With initialization, the 16th element of CocoMelon is 4
With initialization, the 25th element of CocoMelon is 5
With initialization, the 36th element of CocoMelon i

In [4]:
%%writefile initial.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[10] = {1, 2, 3, 4, 5};
    for (int i = 0; i < 10; i++) {
        cout << "With initialization, the "
        << i << "th element of CocoMelon is "
        << CocoMelon[i] << endl;
    }
    return 0;
}

Overwriting initial.cpp


In [5]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic initial.cpp -o initial
./initial

With initialization, the 0th element of CocoMelon is 1
With initialization, the 1th element of CocoMelon is 2
With initialization, the 2th element of CocoMelon is 3
With initialization, the 3th element of CocoMelon is 4
With initialization, the 4th element of CocoMelon is 5
With initialization, the 5th element of CocoMelon is 0
With initialization, the 6th element of CocoMelon is 0
With initialization, the 7th element of CocoMelon is 0
With initialization, the 8th element of CocoMelon is 0
With initialization, the 9th element of CocoMelon is 0


## Prefix sum

In [6]:
%%writefile prefix_sum.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100] = {};
    int PrefixSum[100] = {};
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = i;
    }
    PrefixSum[0] = 0; // is this line necessary?
    for (int i = 1; i < 100; i++) {
        PrefixSum[i] = PrefixSum[i-1] + CocoMelon[i];
    }
    for (int i = 0; i < 11; i++) {
        cout << "the " << i << "th prefix sum is "
        << PrefixSum[i] << endl;
    }
    return 0;
}

Overwriting prefix_sum.cpp


In [7]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic prefix_sum.cpp -o prefix_sum
./prefix_sum

the 0th prefix sum is 0
the 1th prefix sum is 1
the 2th prefix sum is 3
the 3th prefix sum is 6
the 4th prefix sum is 10
the 5th prefix sum is 15
the 6th prefix sum is 21
the 7th prefix sum is 28
the 8th prefix sum is 36
the 9th prefix sum is 45
the 10th prefix sum is 55


## Reverse order

In [8]:
%%writefile reverse.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100] = {};
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = i;
    }
    int MelonCoco[100] = {};
    for (int i = 0; i < 100; i++) {
        MelonCoco[i] = CocoMelon[100 - 1 - i];
    }
    for (int i = 0; i < 100; i++) {
        cout << CocoMelon[i] << " " << MelonCoco[i] << endl;
    }
    return 0;
}

Overwriting reverse.cpp


In [9]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic reverse.cpp -o reverse
./reverse

0 99
1 98
2 97
3 96
4 95
5 94
6 93
7 92
8 91
9 90
10 89
11 88
12 87
13 86
14 85
15 84
16 83
17 82
18 81
19 80
20 79
21 78
22 77
23 76
24 75
25 74
26 73
27 72
28 71
29 70
30 69
31 68
32 67
33 66
34 65
35 64
36 63
37 62
38 61
39 60
40 59
41 58
42 57
43 56
44 55
45 54
46 53
47 52
48 51
49 50
50 49
51 48
52 47
53 46
54 45
55 44
56 43
57 42
58 41
59 40
60 39
61 38
62 37
63 36
64 35
65 34
66 33
67 32
68 31
69 30
70 29
71 28
72 27
73 26
74 25
75 24
76 23
77 22
78 21
79 20
80 19
81 18
82 17
83 16
84 15
85 14
86 13
87 12
88 11
89 10
90 9
91 8
92 7
93 6
94 5
95 4
96 3
97 2
98 1
99 0


## Shift / offset / rotate

In [10]:
%%writefile shift.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100] = {};
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = i;
    }
    int shift;
    cout << "How much do you want to shift? " << endl;
    cin >> shift;
    cout << "You want to shift by " << shift << endl;
    for (; shift; shift--) {
        int temp = CocoMelon[0];
        for (int i = 0; i < 100 - 1; i++) {
            CocoMelon[i] = CocoMelon[i + 1];
        }
        CocoMelon[99] = temp;
    }
    for (int i = 0; i < 100; i++) {
        cout << CocoMelon[i] << " ";
    }
    return 0;
}

Overwriting shift.cpp


In [11]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic shift.cpp -o shift
./shift <<< "12"

How much do you want to shift? 
You want to shift by 12
12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 0 1 2 3 4 5 6 7 8 9 10 11 

In [12]:
%%writefile shift_fast.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100] = {};
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = i;
    }
    int shift;
    cout << "How much do you want to shift? " << endl;
    cin >> shift;
    cout << "You want to shift by " << shift << endl;
    for (int i = 0; i < 100 / 2; i++) {
        int a = CocoMelon[i];
        int b = CocoMelon[100 - 1 - i];
        CocoMelon[i] = b;
        CocoMelon[100 - 1 - i] = a;
    }
    for (int i = 0; i < shift / 2; i++) {
        int a = CocoMelon[i];
        int b = CocoMelon[shift - 1 - i];
        CocoMelon[i] = b;
        CocoMelon[shift - 1 - i] = a;
    }
    for (int i = 0; i < (100 - shift) / 2; i++) {
        int a = CocoMelon[shift + i];
        int b = CocoMelon[100 - 1 - i];
        CocoMelon[shift + i] = b;
        CocoMelon[100 - 1 - i] = a;
    }
    for (int i = 0; i < 100; i++) {
        cout << CocoMelon[i] << " ";
    }
    return 0;
}

Overwriting shift_fast.cpp


In [13]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic shift_fast.cpp -o shift_fast
./shift_fast <<< "12"

How much do you want to shift? 
You want to shift by 12
88 89 90 91 92 93 94 95 96 97 98 99 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 

## Two dimensional arrays

In [14]:
%%writefile matrix.cpp

#include <iostream>
using namespace std;

int main() {
    int Keanu[3][3] = {1, 2, 3, 4, 5};
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << Keanu[i][j] << " ";
        }
        cout << endl;
    }
    return 0;
}

Overwriting matrix.cpp


In [15]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic matrix.cpp -o matrix
./matrix

1 2 3 
4 5 0 
0 0 0 


In [16]:
%%writefile transpose.cpp

#include <iostream>
using namespace std;

int main() {
    int Keanu[3][3] = {{1, 2, 3}, {4, 5}, {6}};
    int Reeves[3][3] = {};
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            Reeves[j][i] = Keanu[i][j];
        }
    }
    cout << "Keanu :" << endl;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << Keanu[i][j];
        }
        cout << endl;
    }
    cout << "Reeves :" << endl;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << Reeves[i][j];
        }
        cout << endl;
    }
    return 0;
}

Overwriting transpose.cpp


In [17]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic transpose.cpp -o transpose
./transpose

Keanu :
123
450
600
Reeves :
146
250
300


In [18]:
%%writefile rotate.cpp

#include <iostream>
using namespace std;

int main() {
    int Keanu[3][3] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
    int Reeves[3][3] = {};
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            Reeves[j][2 - i] = Keanu[i][j];
        }
    }
    cout << "Keanu :" << endl;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << Keanu[i][j];
        }
        cout << endl;
    }
    cout << "Reeves :" << endl;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << Reeves[i][j];
        }
        cout << endl;
    }
    return 0;
}

Overwriting rotate.cpp


In [19]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic rotate.cpp -o rotate
./rotate

Keanu :
123
456
789
Reeves :
741
852
963


## Prime numbers

In [20]:
%%writefile prime.cpp

#include <iostream>
using namespace std;

int main() {
    int Primes[100] = {};
    int n_prime = 0;
    for (int n = 2; n < 10000000; n++) {
        bool is_prime = true;
        for (int i = 0; i < n_prime; i++) {
            if (n % Primes[i] == 0) {
                is_prime = false;
                break;
            }
        }
        if (is_prime) {
            Primes[n_prime] = n;
            n_prime++;
        }
    }
    for (int k = 0; k < 100; k++) {
        cout << Primes[k] << ' ';
    }
    return 0;
}

Overwriting prime.cpp


In [21]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic prime.cpp -o prime
./prime

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541 

In [22]:
list(primes(542))

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541]

## Binomial coefficient

In [23]:
%%writefile binom.cpp

#include <iostream>
using namespace std;

int main() {
    int Pascal[20][20] = {};
    for (int n = 0; n < 20; n++) {
        for (int k = 0; k <= n; k++) {
            if (k == 0 || k == n) {
                Pascal[n][k] = 1;
            } else {
                Pascal[n][k] = Pascal[n-1][k-1] + Pascal[n-1][k];
            }
        }
    }
    for (int a = 0; a < 20; a++) {
        for (int b = 0; b <= a; b++) {
            cout << Pascal[a][b] << ' ';
        }
        cout << endl;
    }
    return 0;
}

Overwriting binom.cpp


In [24]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic binom.cpp -o binom
./binom

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 
1 6 15 20 15 6 1 
1 7 21 35 35 21 7 1 
1 8 28 56 70 56 28 8 1 
1 9 36 84 126 126 84 36 9 1 
1 10 45 120 210 252 210 120 45 10 1 
1 11 55 165 330 462 462 330 165 55 11 1 
1 12 66 220 495 792 924 792 495 220 66 12 1 
1 13 78 286 715 1287 1716 1716 1287 715 286 78 13 1 
1 14 91 364 1001 2002 3003 3432 3003 2002 1001 364 91 14 1 
1 15 105 455 1365 3003 5005 6435 6435 5005 3003 1365 455 105 15 1 
1 16 120 560 1820 4368 8008 11440 12870 11440 8008 4368 1820 560 120 16 1 
1 17 136 680 2380 6188 12376 19448 24310 24310 19448 12376 6188 2380 680 136 17 1 
1 18 153 816 3060 8568 18564 31824 43758 48620 43758 31824 18564 8568 3060 816 153 18 1 
1 19 171 969 3876 11628 27132 50388 75582 92378 92378 75582 50388 27132 11628 3876 969 171 19 1 


In [25]:
for n in range(20):
    for k in range(n + 1):
        print(binomial(n, k), end=' ')
    print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 
1 6 15 20 15 6 1 
1 7 21 35 35 21 7 1 
1 8 28 56 70 56 28 8 1 
1 9 36 84 126 126 84 36 9 1 
1 10 45 120 210 252 210 120 45 10 1 
1 11 55 165 330 462 462 330 165 55 11 1 
1 12 66 220 495 792 924 792 495 220 66 12 1 
1 13 78 286 715 1287 1716 1716 1287 715 286 78 13 1 
1 14 91 364 1001 2002 3003 3432 3003 2002 1001 364 91 14 1 
1 15 105 455 1365 3003 5005 6435 6435 5005 3003 1365 455 105 15 1 
1 16 120 560 1820 4368 8008 11440 12870 11440 8008 4368 1820 560 120 16 1 
1 17 136 680 2380 6188 12376 19448 24310 24310 19448 12376 6188 2380 680 136 17 1 
1 18 153 816 3060 8568 18564 31824 43758 48620 43758 31824 18564 8568 3060 816 153 18 1 
1 19 171 969 3876 11628 27132 50388 75582 92378 92378 75582 50388 27132 11628 3876 969 171 19 1 


Another way to compute the binomial coefficient is by the definition
$\binom nk = \frac{n!}{k! (n-k)!}$.

But computing $n!$ is dangerous because it might overflow
even though \binom nk does not overflow.
So we can instead use the recurrence relation
$\binom nk = \binom{n-1}{k-1} \cdot \frac nk$.

## Array summary

In [26]:
%%writefile summary.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100];
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = i;
    }
    int sum = 0;
    int min = CocoMelon[0];
    int max = CocoMelon[0];
    for (int i = 0; i < 100; i++) {
        sum += CocoMelon[i];
        if (CocoMelon[i] < min) {
            min = CocoMelon[i];
        }
        if (CocoMelon[i] > max) {
            max = CocoMelon[i];
        }
    }
    cout << "Sum: " << sum << endl;
    cout << "Average: " << double(sum) / 100 << endl;
    cout << "Min: " << min << endl;
    cout << "Max: " << max << endl;
    return 0;
}

Overwriting summary.cpp


In [27]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic summary.cpp -o summary
./summary

Sum: 4950
Average: 49.5
Min: 0
Max: 99


## Sorting

In [28]:
%%writefile sort.cpp

#include <iostream>
using namespace std;

int main() {
    int CocoMelon[100];
    for (int i = 0; i < 100; i++) {
        CocoMelon[i] = (i * 37 + 50) % 100;
        cout << CocoMelon[i] << " ";
    }
    cout << endl;
    bool sorted = false;
    while (!sorted) {
        sorted = true;
        for (int i = 0; i < 99; i++) {
            if (CocoMelon[i] > CocoMelon[i + 1]) {
                int a = CocoMelon[i];
                int b = CocoMelon[i + 1];
                CocoMelon[i] = b;
                CocoMelon[i + 1] = a;
                sorted = false;
            }
        }
    }
    for (int i = 0; i < 100; i++) {
        cout << CocoMelon[i] << " ";
    }
    return 0;
}

Overwriting sort.cpp


In [29]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic sort.cpp -o sort
./sort

50 87 24 61 98 35 72 9 46 83 20 57 94 31 68 5 42 79 16 53 90 27 64 1 38 75 12 49 86 23 60 97 34 71 8 45 82 19 56 93 30 67 4 41 78 15 52 89 26 63 0 37 74 11 48 85 22 59 96 33 70 7 44 81 18 55 92 29 66 3 40 77 14 51 88 25 62 99 36 73 10 47 84 21 58 95 32 69 6 43 80 17 54 91 28 65 2 39 76 13 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

## Vote counting

In [30]:
%%writefile vote.cpp

#include <iostream>
#include <random>
using namespace std;

int main() {
    mt19937 m7(20250917);
    int Votes[5] = {};
    for (int i = 0; i < 100; i++) {
        int vote = m7() % 5;
        Votes[vote]++;
    }
    for (int i = 0; i < 5; i++) {
        cout << "Candidate " << i
        << " received " << Votes[i] << " votes." << endl;
    }
    return 0;
}

Overwriting vote.cpp


In [31]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic vote.cpp -o vote
./vote

Candidate 0 received 27 votes.
Candidate 1 received 15 votes.
Candidate 2 received 21 votes.
Candidate 3 received 22 votes.
Candidate 4 received 15 votes.


## Matrix multiplication

In [32]:
%%writefile matrix.cpp

#include <iostream>
using namespace std;

int main() {
    int A[3][3] = {1, 2, 3, 4, 5, 6, 7, 8, 9};
    int B[3][3] = {10, 11, 12, 13, 14, 15, 16, 17, 18};
    int C[3][3] = {};
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            for (int k = 0; k < 3; k++) {
                C[i][k] += A[i][j] * B[j][k];
            }
        }
    }
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << C[i][j] << " ";
        }
        cout << endl;
    }
    return 0;
}

Overwriting matrix.cpp


In [33]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic matrix.cpp -o matrix
./matrix

84 90 96 
201 216 231 
318 342 366 


In [34]:
A = matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = matrix([
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])
A * B

[ 84  90  96]
[201 216 231]
[318 342 366]

# RREF (no pivoting)

In [35]:
%%writefile rref.cpp

#include <iostream>
#include <cmath>
using namespace std;

int main() {
    float A[3][3] = {};
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            A[i][j] = (7 * i + 3 * j + 5) % 13;
        }
    }
    for (int i = 0; i < 3; i++) {
        for (int k = 0; k < 3; k++) {
            cout << A[i][k] << ' ';
        }
        cout << endl;
    }
    for (int i = 0; i < 3; i++) { // index of pivot
        for (int j = i + 1; j < 3; j++) { // index of row being eliminated
            float ratio = A[j][i] / A[i][i];
            for (int k = 0; k < 3; k++) { // index of column being eliminated
                A[j][k] -= ratio * A[i][k];
            }
        }
    }
    cout << "After gaussian elimination" << endl;
    for (int i = 0; i < 3; i++) {
        for (int k = 0; k < 3; k++) {
            cout << A[i][k] << ' ';
        }
        cout << endl;
    }
    cout << "Determinant " << A[0][0] * A[1][1] * A[2][2];
    return 0;
}

Overwriting rref.cpp


In [36]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic rref.cpp -o rref
./rref

5 8 11 
12 2 5 
6 9 12 
After gaussian elimination
5 8 11 
0 -17.2 -21.4 
0 0 -0.453489 
Determinant 39

In [37]:
f = lambda i, j: (7 * i + 3 * j + 5) % 13
A = matrix(3, 3, f)
A

[ 5  8 11]
[12  2  5]
[ 6  9 12]

In [38]:
P, L, U = A.LU(pivot='nonzero')
matrix(RR, U)

[  5.00000000000000   8.00000000000000   11.0000000000000]
[ 0.000000000000000  -17.2000000000000  -21.4000000000000]
[ 0.000000000000000  0.000000000000000 -0.453488372093023]

## Convex hull

In [39]:
%%writefile arch.cpp

#include <iostream>
#include <random>
#include <unistd.h>
using namespace std;

int main() {
    mt19937 m7(20250917);
    float Arch[20] = {};
    for (int i = 0; i < 20; i++) {
        int height = i * (20 - i) + 10;
        int height_random = m7() % height;
        Arch[i] = height_random;
    }
    bool converging = false;
    while (!converging) {
        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < Arch[i]; j++) {
                cout << ")";
            }
            cout << endl;
        }
        sleep(1);
        converging = true;
        for (int i = 1; i < 20 - 1; i++) {
            float a = Arch[i - 1];
            float b = Arch[i];
            float c = Arch[i + 1];
            if (a + c > 2 * b + 1e-2) {
                b = (a + c) / 2;
                Arch[i] = b;
                converging = false;
            }
        }
    }
    return 0;
}

Overwriting arch.cpp


In [40]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic arch.cpp -o arch
echo "run this on terminal, not here"

run this on terminal, not here


## PDE

This is what a high-end CPU looks like from side view.

```C++
    int Fins[15][10] = {
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0}, 
        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}, 
        {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}, 
    } 
```

Here `2` is the actual CPU that generates heat,
`1` is the fins, and `0` is the air.

CPU generates heat at a rate of $g^\circ$ C per second per unit length squared.
Within CPU, heat transfers at a rate of $(\delta/50)^\circ$ C per second per unit length,
where $\delta$ is the temperature difference.
At the contact surface between the CPU and the fins,
heat transfers at a rate of $(\delta/20)^\circ$ C per second per unit length.
Within the fin, heat transfers at a rate of $(\delta/10)^\circ$ C per second per unit length.
At the contact surface between the fins and the air,
heat transfers at a rate of $(\delta/100)^\circ$ C per second per unit length.
And the air is always at $30^\circ$ C.

Now you are asked to write a program that takes `double g` as input
and outputs the temperature of the hottest point of the CPU after a long long time,
so long that the temperature changes by at most $(1/1000000)^\circ$ C per second.


In [ ]:
%%writefile fin.cpp

#include <iostream>
#include <vector>
using namespace std;
const int ROWS = 10;
const int COLS = 15;

int Fins[ROWS][COLS] = {
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0},
    {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
    {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
};

double SimulateCpuTemperature(double g) {
    // Initialize temperature grid
    vector<vector<double>> Temper(ROWS, vector<double>(COLS, 30));
    vector<vector<double>> TemNew = Temper;
    bool still_cooling = true;
    while (still_cooling) {
        for (int i = 0; i < ROWS; ++i) {
            for (int j = 1; j < COLS; ++j) {
                double tdif = Temper[i][j] - Temper[i][j-1];
                if (Fins[i][j-1] + Fins[i][j] == 1) { // fin-air
                    if (Fins[i][j-1]) TemNew[i][j-1] += tdif / 100.;
                    if (Fins[i][j]) TemNew[i][j] -= tdif / 100.;
                }
                if (Fins[i][j-1] + Fins[i][j] == 2) { // fin-fin
                    TemNew[i][j-1] += tdif / 10.;
                    TemNew[i][j] -= tdif / 10.;
                }
                if (Fins[i][j-1] + Fins[i][j] == 3) { // fin-cpu
                    TemNew[i][j-1] += tdif / 20.;
                    TemNew[i][j] -= tdif / 20.;
                }
                if (Fins[i][j-1] + Fins[i][j] == 4) { // cpu-cpu
                    TemNew[i][j-1] += tdif / 50.;
                    TemNew[i][j] -= tdif / 50.;
                }
            }
        }
        for (int i = 1; i < ROWS; ++i) {
            for (int j = 0; j < COLS; ++j) {
                double tdif = Temper[i][j] - Temper[i-1][j];
                if (Fins[i-1][j] + Fins[i][j] == 1) { // fin-air
                    if (Fins[i-1][j]) TemNew[i-1][j] += tdif / 100.;
                    if (Fins[i][j]) TemNew[i][j] -= tdif / 100.;
                }
                if (Fins[i-1][j] + Fins[i][j] == 2) { // fin-fin
                    TemNew[i-1][j] += tdif / 10.;
                    TemNew[i][j] -= tdif / 10.;
                }
                if (Fins[i-1][j] + Fins[i][j] == 3) { // fin-cpu
                    TemNew[i-1][j] += tdif / 20.;
                    TemNew[i][j] -= tdif / 20.;
                }
                if (Fins[i-1][j] + Fins[i][j] == 4) { // cpu-cpu
                    TemNew[i-1][j] += tdif / 50.;
                    TemNew[i][j] -= tdif / 50.;
                }
            }
        }

        still_cooling = false;
        for (int j = 0; j < COLS; j++) {
            if (Fins[9][j] != 2) break;
            TemNew[9][j] += g;
            if (abs(TemNew[9][j] - Temper[9][j]) > 1e-6) {
                still_cooling = true;
            }
        }
        Temper = TemNew;
    }

    for (int i = 0; i < ROWS; ++i) {
        for (int j = 0; j < COLS; ++j) {
            cout << Temper[i][j] << " ";
        }
        cout << endl;
    }

    double max_cpu_temp = 30;
    for (int j = 0; j < COLS; ++j) {
        max_cpu_temp = max(max_cpu_temp, Temper[9][j]);
    }
    return max_cpu_temp;
}

int main() {
    double TestingCases[10] = {0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.05};
    // double TestingCases[10] = {0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0};
    double Answers[10] = {40.4425, 47.4043, 54.366, 61.3278, 68.2896, 75.2513, 82.2131, 89.1748, 96.1366, 103.098};
    for (int ndx = 0; ndx < 10; ndx ++) {
        double g = TestingCases[ndx];
        double hottest = SimulateCpuTemperature(g);
        cout << int((hottest - Answers[ndx]) * 10000) << "/10000";
        cout << "   g: " << g << " --> Hottest: " << hottest << "\n";
    }
    return 0;
}
/*
 * 0.1 --> 42.52
 * 0.2 --> 55.0403
 * 0.3 --> 67.5607
 * 0.4 --> 80.0811
 * 0.5 --> 92.6014
 * 0.6 --> 105.122
 * 0.7 --> 117.642
 * 0.8 --> 130.163
 * 0.9 --> 142.683
 * 1.0 --> 155.203
 */

Writing fin.cpp


In [45]:
%%bash

g++-14 -std=c++26 -Wall -Wextra -Wpedantic fin.cpp -o fin
./fin

30 30.3269 30 30.3147 30 30.31 30 30.3087 30 30.31 30 30.3147 30 30.3269 30 
30 30.3922 30 30.3777 30 30.3719 30 30.3704 30 30.3719 30 30.3777 30 30.3922 30 
30 30.5361 30 30.5162 30 30.5083 30 30.5063 30 30.5083 30 30.5162 30 30.5361 30 
30 30.7871 30 30.7579 30 30.7464 30 30.7433 30 30.7464 30 30.7579 30 30.7871 30 
30 31.1955 30 31.1512 30 31.1337 30 31.1291 30 31.1337 30 31.1512 30 31.1955 30 
30 31.8431 30 31.7748 30 31.7478 30 31.7406 30 31.7478 30 31.7748 30 31.8431 30 
30 32.8593 30 32.7533 30 32.7114 30 32.7003 30 32.7114 30 32.7533 30 32.8593 30 
30 34.4474 30 34.2824 30 34.2173 30 34.2001 30 34.2173 30 34.2824 30 34.4474 30 
37.5913 36.9249 37.1632 36.668 36.9908 36.5667 36.9289 36.5399 36.9289 36.5667 36.9908 36.668 37.1632 36.9249 37.5913 
40.4425 40.0705 40.0626 39.8035 39.8829 39.6927 39.8174 39.6632 39.8174 39.6927 39.8829 39.8035 40.0626 40.0705 40.4425 
0/10000   g: 0.15 --> Hottest: 40.4425
30 30.5448 30 30.5246 30 30.5166 30 30.5145 30 30.5166 30 30.5246 30 30.5448 