# NumPy

A NumPy array is a function, for example
$$ A: [4] \times [5] \times [6] \to [2^{64}]. $$
In this case `A.shape` is going to be `[4, 5, 6]`,
and `A.dtype` is going to be `uint64`

In [80]:
import numpy as np

A = np.zeros([4, 5, 6])
A

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [81]:
A.shape, A.dtype

((4, 5, 6), dtype('float64'))

Why do we need multi-dimensional array?

- Each pixel has three color channels (R, G, and B)
- Each picture is a w-by-h array of pixels
- A 3D X-ray scan has one more dimension
- A video has one more dimension: time

![poke](poke.jpg)

- The vertical axis is generation (different game)
- The horizontal axis--small step is evolution.
- The horizontal axis--large step is element/type.

In [82]:
# Initialize an array

A = np.full([4, 5, 6], np.nan)
B = np.full([4, 5, 6], -404)
C = np.full_like(B, np.nan, dtype='float')

# This means full_like(B) = full(B.shape)
# Fill in illegal values to remind yourself to populate them later.

In [83]:
# Special arrays

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# Evenly spaced numbers

np.linspace(10, 20, 101)

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [85]:
np.linspace(10, 20, 100).reshape([10, 10])

array([[10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
        10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091],
       [11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
        11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192],
       [12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
        12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293],
       [13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
        13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394],
       [14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
        14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495],
       [15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
        15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596],
       [16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
        16.56565657, 16.66666667, 16.76767677

### Unary Functions

In [86]:
# Scalar operations

np.arange(1, 10) * 2 - 1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [87]:
np.arange(100).reshape([10, 10]) * 2 - 1

array([[ -1,   1,   3,   5,   7,   9,  11,  13,  15,  17],
       [ 19,  21,  23,  25,  27,  29,  31,  33,  35,  37],
       [ 39,  41,  43,  45,  47,  49,  51,  53,  55,  57],
       [ 59,  61,  63,  65,  67,  69,  71,  73,  75,  77],
       [ 79,  81,  83,  85,  87,  89,  91,  93,  95,  97],
       [ 99, 101, 103, 105, 107, 109, 111, 113, 115, 117],
       [119, 121, 123, 125, 127, 129, 131, 133, 135, 137],
       [139, 141, 143, 145, 147, 149, 151, 153, 155, 157],
       [159, 161, 163, 165, 167, 169, 171, 173, 175, 177],
       [179, 181, 183, 185, 187, 189, 191, 193, 195, 197]])

In [88]:
np.sqrt(np.arange(10))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [89]:
np.sin(np.arange(10))

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [90]:
np.arange(10) % 2 >= 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [91]:
# Turning a scalar function into a array function

def f(x): return x**2 + 1

np.vectorize(f)(np.arange(10))

array([ 1,  2,  5, 10, 17, 26, 37, 50, 65, 82])

### Indexing

In [92]:
# Single integer to select an element

powers = (2**np.arange(10))
powers[5]

np.int64(32)

In [93]:
# A list of integers to select multiple

primes = [2, 3, 5, 7]
powers[primes]

array([  4,   8,  32, 128])

In [94]:
# Compare this to the next one

primes = [0, 0, 1, 1, 0, 1, 0, 1, 0, 0]
powers[primes]

array([1, 1, 2, 2, 1, 2, 1, 2, 1, 1])

In [95]:
# Use a boolean to filter an array

primes = np.array(primes, dtype='bool')
powers[primes]

array([  4,   8,  32, 128])

In [96]:
# Generator also works

even = (np.arange(10) % 2 == 0)
powers[even]

array([  1,   4,  16,  64, 256])

### Binary Functions

In [97]:
# Entry-wise operations

np.arange(10) * np.arange(10)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [98]:
# Multiplication table

A = np.arange(1, 11)
A0 = A[:, np.newaxis]
A0

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [99]:
B = np.arange(1, 10)
B1 = B[np.newaxis, :]
B1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [100]:
A0 * B1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81],
       [10, 20, 30, 40, 50, 60, 70, 80, 90]])

Explanation:
$$ A: [11] \to \mathbb N $$
$$ B: [10] \to \mathbb N $$
Then $A \cdot B$ is at best $[10] \to \mathbb N$.

But we make 
$$ A_0: [11] \times [10] \to \mathbb N $$
by
$$ A_0(x, y) = A(x). $$
Similarly, we make
$$ B_1: [11] \times [10] \to \mathbb N $$
by
$$ B_1(x, y) = B(y). $$
Then
$A_0 \cdot B_1: [11] \times [10] \to \mathbb N$ is what we want.

In [101]:
# Multiplication is commutative

B1 * A0

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81],
       [10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [102]:
# Vandermonde matrix

(np.arange(7) - 3)[:, np.newaxis] ** np.arange(7)[np.newaxis, :]

array([[   1,   -3,    9,  -27,   81, -243,  729],
       [   1,   -2,    4,   -8,   16,  -32,   64],
       [   1,   -1,    1,   -1,    1,   -1,    1],
       [   1,    0,    0,    0,    0,    0,    0],
       [   1,    1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32,   64],
       [   1,    3,    9,   27,   81,  243,  729]])

In [103]:
# Geometric sequence

np.exp(np.arange(10) * 2*np.pi*1j/10)

array([ 1.        +0.00000000e+00j,  0.80901699+5.87785252e-01j,
        0.30901699+9.51056516e-01j, -0.30901699+9.51056516e-01j,
       -0.80901699+5.87785252e-01j, -1.        +1.22464680e-16j,
       -0.80901699-5.87785252e-01j, -0.30901699-9.51056516e-01j,
        0.30901699-9.51056516e-01j,  0.80901699-5.87785252e-01j])

In [104]:
# Two geometric sequences combined

np.exp(np.arange(10)[:, np.newaxis] * 2*np.pi*1j/10) ** np.arange(10)[np.newaxis, :]

array([[ 1.        +0.00000000e+00j,  1.        +0.00000000e+00j,
         1.        +0.00000000e+00j,  1.        +0.00000000e+00j,
         1.        +0.00000000e+00j,  1.        +0.00000000e+00j,
         1.        +0.00000000e+00j,  1.        +0.00000000e+00j,
         1.        +0.00000000e+00j,  1.        +0.00000000e+00j],
       [ 1.        +0.00000000e+00j,  0.80901699+5.87785252e-01j,
         0.30901699+9.51056516e-01j, -0.30901699+9.51056516e-01j,
        -0.80901699+5.87785252e-01j, -1.        +0.00000000e+00j,
        -0.80901699-5.87785252e-01j, -0.30901699-9.51056516e-01j,
         0.30901699-9.51056516e-01j,  0.80901699-5.87785252e-01j],
       [ 1.        +0.00000000e+00j,  0.30901699+9.51056516e-01j,
        -0.80901699+5.87785252e-01j, -0.80901699-5.87785252e-01j,
         0.30901699-9.51056516e-01j,  1.        -1.11022302e-16j,
         0.30901699+9.51056516e-01j, -0.80901699+5.87785252e-01j,
        -0.80901699-5.87785252e-01j,  0.30901699-9.51056516e-01j],
       

This is the Fourier matrix
$$
\begin{bmatrix}
    1 & 1 & 1 & 1 & 1 & \ddots
    \\
    1 & \omega & \omega^2 & \omega^3 & \ddots
    \\
    1 & \omega^2 & \omega^4 & \ddots
    \\
    1 & \omega^3 & \ddots
    \\
    1 & \ddots
    \\
    \ddots
\end{bmatrix}
$$

### Axis-Wise Functions

In [105]:
# Use reshape to create creative arrays

A = np.arange(24).reshape([2, 3, 4])
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [106]:
A.min(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
A.min(axis=1)

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [108]:
A.min(axis=2)

array([[ 0,  4,  8],
       [12, 16, 20]])

In [109]:
A.sum(axis=0) # same logic
A.mean(axis=1) # same logic
A.std(axis=2) # same logic

array([[1.11803399, 1.11803399, 1.11803399],
       [1.11803399, 1.11803399, 1.11803399]])

### Broadcasting

In [110]:
A = np.zeros([4, 5, 6, 7, 8, 9])
B = np.zeros([7, 8, 9])
A + B # They add?

array([[[[[[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          ...,

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0.,

In [111]:
A = np.zeros([4, 5, 6, 7, 8, 9])
B = np.zeros([4, 5, 6])
A + B # Whaat happens?

ValueError: operands could not be broadcast together with shapes (4,5,6,7,8,9) (4,5,6) 

If B.shape is a suffix of A.shape,
then B will be **broadcast** to A.shape.
That is,
$$ B'(a, b, c, x, y, z) = B(x, y, z). $$
It is also equivalent to 
`B_ = B[np.newaxis, np.newaxis, np.newaxis, :, :, :]`

Special case: If `B` is a scalar, `B.shape` is the empty tuple `()`,
which is a suffix of any shape. This means that a scalar can be broadcast to any shape.

That is to say, `A + 10` is a special case of broadcasting
where we define `ten[a, b, c] = 10` and compute `A + ten`.

But what if we really want to add `np.zeros([4, 5, 6])` to `np.zeros([4, 5, 6, 7, 8, 9])`?

In [33]:
(A + B[:, :, :, np.newaxis, np.newaxis, np.newaxis]).shape

(4, 5, 6, 7, 8, 9)

## einops

In [112]:
import numpy as np
from einops import rearrange

In [114]:
# Permuting the axis (rotating the hypercube)
# (may or may not change memory layout)

A = np.zeros([4, 5, 6, 7, 8, 9])
AA = rearrange(A, 'a b c x y z -> x y z a b c')
AA.shape

(7, 8, 9, 4, 5, 6)

This is equivalent to letting
$$ A: [4] \times [5] \times [6] \times [7] \times [8] \times [9] \to \mathbb N $$
$$ A': [7] \times [8] \times [9] \times [4] \times [5] \times [6] \to \mathbb N $$
and $A'(x, y, z, a, b, c) = A(a, b, c, x, y, z)$.

In [37]:
B = np.zeros([4, 5, 6])
(AA + B).shape

# Now they add because the suffixes of the shapes match

(7, 8, 9, 4, 5, 6)

In [115]:
# Arbitrary permutation works

rearrange(AA, 'a b c x y z -> a x b y c z').shape

(7, 4, 8, 5, 9, 6)

In [116]:
# 1 is equivalent to np.newaxis

BB = rearrange(B, 'a b c -> a b c 1 1 1')
BB.shape

(4, 5, 6, 1, 1, 1)

In [40]:
(A + BB).shape

(4, 5, 6, 7, 8, 9)

Summary:
broadcasting will work if  
A.shape is a suffix of B.shape  
(or B.shape is a suffix of A.shape),  
and any `1` in shape is treated as a wildcard.

### repeat

In [117]:
# More than one is repetition

from einops import repeat

repeat(np.arange(10), 'a -> a 3')

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8],
       [9, 9, 9]])

In [118]:
# The repetition can happen in the same axis

repeat(np.arange(12).reshape([3, 4]), 'a b -> (a 5) b')

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [120]:
# Reshape (flattening)

A = np.arange(24)
B = A.reshape([2, 3, 4])
C = rearrange(B, 'a b c -> (a b c)')
C == A

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [122]:
# Unflattening

A = np.arange(24)
B = A.reshape([2, 3, 4])
D = rearrange(A, '(a b c) -> a b c', a=2, b=3, c=4)
(B == D).all()

np.True_

In [45]:
E = np.zeros([4, 5, 6])
rearrange(E, 'a b c -> (a b c)').shape

(120,)

In [46]:
rearrange(E, 'a b c -> (a b) c').shape

(20, 6)

In [47]:
rearrange(E, 'a b c -> a (b c)').shape

(4, 30)

In [48]:
# Kronecker product

np.kron([1, 2, 3], [4, 5, 6, 7]).shape

(12,)

In [128]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[1, 1], [1, 1]])
np.kron(A, B)

array([[1, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1]])

In [129]:
A = np.zeros([4, 5, 6])
B = np.zeros([7, 8, 9])
np.kron(A, B).shape

(28, 40, 54)

In [132]:
# Equivalent way to produce kronecker product

AA = rearrange(A, 'a b c -> a 1 b 1 c 1')
AA.shape

(4, 1, 5, 1, 6, 1)

In [131]:
BB = rearrange(B, 'x y z -> 1 x 1 y 1 z')
BB.shape

(1, 7, 1, 8, 1, 9)

In [53]:
(AA * BB).shape

(4, 7, 5, 8, 6, 9)

In [54]:
rearrange(AA * BB, 'a x b y c z -> (a x) (b y) (c z)').shape

(28, 40, 54)

### pack/unpack

In [134]:
# The generalization of np.stack
# And similar to np.block

from einops import pack, unpack

a = np.zeros([2, 3, 4])
b = np.zeros([2, 3, 5])
c = np.zeros([2, 3, 6])

packed, ps = pack([a, b, c], 'x y *')

packed.shape

(2, 3, 15)

In [135]:
ps

[(4,), (5,), (6,)]

In [77]:
# Unpack is the reverse of pack

A, B, C = unpack(packed, ps, 'x y *')
A.shape, B.shape, C.shape

((2, 3, 4), (2, 3, 5), (2, 3, 6))

In [78]:
a = np.zeros([2, 2, 11])
b = np.zeros([3, 3, 11])
c = np.zeros([4, 4, 11])

packed, ps = pack([a, b, c], '* z')

packed.shape

(29, 11)

In [79]:
ps

[(2, 2), (3, 3), (4, 4)]

### reduce

In [136]:
# The Einstein way to apply sum (also mean, std, etc.)

from einops import reduce

reduce(np.zeros([4, 5, 6]), 'a b c -> a c', 'sum').shape

(4, 6)

In [137]:
np.zeros([4, 5, 6]).sum(axis=1).shape

(4, 6)

### einsum

In [138]:
A = np.zeros([4, 5, 6])
B = np.zeros([6, 7])
np.einsum('wxy, yz -> wxz', A, B)

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

The sum is a function
$$ C: [4] \times [5] \times [7] \to \mathbb N $$
such that
$$ C(w, x, z) = \sum_{y=1}^6 A(w, x, y) \cdot B(y, z) $$

In [ ]:
reduce(rearrange(A, 'w x y -> w x y 1') * rearrange(B, 'y z -> 1 1 y z'), 'w x y z -> w x z', 'sum')

In [139]:
# Extract diagonal
A = np.arange(100).reshape([10, 10])
np.einsum('ii -> i', A)

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [140]:
# Trace
np.einsum('ii -> ', A)

np.int64(495)

In [141]:
# Inner product
np.einsum('i, i -> ', np.arange(10), np.arange(10))

np.int64(285)

In [142]:
# Kronecker product
np.einsum('i j, k l -> i k j l', np.arange(4).reshape([2, 2]), np.arange(4).reshape([2, 2]))

array([[[[0, 0],
         [0, 1]],

        [[0, 0],
         [2, 3]]],


       [[[0, 2],
         [0, 3]],

        [[4, 6],
         [6, 9]]]])

In [143]:
# Matrix multiplication
np.einsum('i j, j k -> i k', np.arange(4).reshape([2, 2]), np.arange(4).reshape([2, 2]))

array([[ 2,  3],
       [ 6, 11]])

In [146]:
# The at symbol is a shorthand for matrix multiplication

np.array([[0, 1], [2, 3]]) @ np.array([[0, 1], [2, 3]])

array([[ 2,  3],
       [ 6, 11]])